/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientWindow.java
 *
 * Created on Apr 28, 2012, 8:23:37 PM
 */
package messengerproject;

import java.awt.event.KeyEvent;

/**
 *
 * @author alagaranandrajendran
 */
public class ClientWindow extends javax.swing.JFrame {

    private MessengerProject Messenger_Main;
    private String Client_Name;
    
    
    /** Creates new form ClientWindow */
    public ClientWindow(MessengerProject App, String Client_Name)
    {
        initComponents();
        this.Messenger_Main = App;
        this.Client_Name = Client_Name;
        setTitle(Messenger_Main.Get_UserName()+"-->"+Client_Name);
    }
    
    
    
    
    //Update the Chat history
    public void Chat_History(String History)
    {
        txt_ChatHistory.setText(History);
    }
    
    public void Exit_Window()
    {
        try{
            this.setVisible(false);
            this.dispose();
            
        }
        catch(Exception e)
        {}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_CloseSession = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ChatHistory = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Data = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_CloseSession.setText("Close Session");
        btn_CloseSession.setLocation(new java.awt.Point(-32641, -32720));
        btn_CloseSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CloseSessionMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(txt_ChatHistory);

        txt_Data.setColumns(20);
        txt_Data.setLineWrap(true);
        txt_Data.setRows(5);
        txt_Data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_DataKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txt_Data);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(138, 138, 138)
                .add(btn_CloseSession)
                .addContainerGap(170, Short.MAX_VALUE))
            .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(btn_CloseSession)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(2, 2, 2)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 265, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn_CloseSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CloseSessionMouseClicked
// TODO add your handling code here:
    
    //Event for handing the Session Close
    Messenger_Main.Close_Session(Client_Name);
    try{
        this.dispose();
    }
    catch(Exception e)
    {}
    
}//GEN-LAST:event_btn_CloseSessionMouseClicked

private void txt_DataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DataKeyPressed
// TODO add your handling code here:
    
    if(evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        String Msg = txt_Data.getText();
        Messenger_Main.Send_Msg(Client_Name, Msg.trim());
        txt_Data.setText(null);
    }
}//GEN-LAST:event_txt_DataKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CloseSession;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane txt_ChatHistory;
    private javax.swing.JTextArea txt_Data;
    // End of variables declaration//GEN-END:variables
}
