/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginForm.java
 *
 * Created on Apr 28, 2012, 8:33:15 PM
 */
package messengerproject;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author alagaranandrajendran
 */
public class LoginForm extends javax.swing.JFrame {

    MessengerProject App;
    
    /** Creates new form LoginForm */
    public LoginForm(MessengerProject App) {
        this.App = App;
        
        initComponents();
        
        btn_Register.setVisible(false);
        lbl_Warning.setVisible(false);
        lbl_CfmPassword.setVisible(false);
        txt_Cfm_Password.setVisible(false);
        btn_RegCancel.setVisible(false);
        
        // Determine the new location of the window
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
        
    }
    
    
    public void Set_Warning(String Msg)
    {
        txt_Cfm_Password.setText("");
        txt_Password.setText("");
        lbl_Warning.setText(Msg);
        lbl_Warning.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Username = new javax.swing.JLabel();
        txt_Username = new javax.swing.JTextField();
        lbl_Password = new javax.swing.JLabel();
        txt_Password = new javax.swing.JTextField();
        lbl_CfmPassword = new javax.swing.JLabel();
        txt_Cfm_Password = new javax.swing.JTextField();
        btn_Login = new javax.swing.JButton();
        btn_Register = new javax.swing.JButton();
        btn_Cancel = new javax.swing.JButton();
        btn_RegCancel = new javax.swing.JButton();
        btn_NewUser = new javax.swing.JButton();
        lbl_Warning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Username.setText("User Name:");

        lbl_Password.setText("Password:");

        lbl_CfmPassword.setText("Confirm Password:");

        btn_Login.setText("Login");
        btn_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LoginMouseClicked(evt);
            }
        });

        btn_Register.setText("Register");
        btn_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RegisterMouseClicked(evt);
            }
        });

        btn_Cancel.setText("Cancel");
        btn_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CancelMouseClicked(evt);
            }
        });

        btn_RegCancel.setText("Cancel");
        btn_RegCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_RegCancelMouseClicked(evt);
            }
        });

        btn_NewUser.setText("New User?");
        btn_NewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_NewUserMouseClicked(evt);
            }
        });

        lbl_Warning.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Warning.setText("asdadasdasdasdasdasdasdsd");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 376, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 25, Short.MAX_VALUE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(46, 46, 46)
                            .add(lbl_Username)
                            .add(14, 14, 14)
                            .add(txt_Username, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(55, 55, 55)
                            .add(lbl_Password)
                            .add(14, 14, 14)
                            .add(txt_Password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(lbl_CfmPassword)
                            .add(14, 14, 14)
                            .add(txt_Cfm_Password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(19, 19, 19)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(btn_Login)
                                        .add(layout.createSequentialGroup()
                                            .add(30, 30, 30)
                                            .add(btn_Register)))
                                    .add(45, 45, 45)
                                    .add(btn_RegCancel))
                                .add(layout.createSequentialGroup()
                                    .add(100, 100, 100)
                                    .add(btn_Cancel))
                                .add(layout.createSequentialGroup()
                                    .add(200, 200, 200)
                                    .add(btn_NewUser))))
                        .add(layout.createSequentialGroup()
                            .add(9, 9, 9)
                            .add(lbl_Warning, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 310, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(0, 24, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 202, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 19, Short.MAX_VALUE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(6, 6, 6)
                            .add(lbl_Username))
                        .add(txt_Username, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(8, 8, 8)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(6, 6, 6)
                            .add(lbl_Password))
                        .add(txt_Password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(8, 8, 8)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(6, 6, 6)
                            .add(lbl_CfmPassword))
                        .add(txt_Cfm_Password, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(8, 8, 8)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(btn_Login)
                        .add(layout.createSequentialGroup()
                            .add(10, 10, 10)
                            .add(btn_Register))
                        .add(layout.createSequentialGroup()
                            .add(10, 10, 10)
                            .add(btn_RegCancel))
                        .add(btn_Cancel)
                        .add(btn_NewUser))
                    .add(1, 1, 1)
                    .add(lbl_Warning)
                    .add(0, 19, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LoginMouseClicked
// TODO add your handling code here:
    //Send the username and password to the server
    //String Data = "Login:"+txt_Username.getText()+":"+txt_Password.getText();
    App.User_Login(0, txt_Username.getText(),txt_Password.getText());
}//GEN-LAST:event_btn_LoginMouseClicked

private void btn_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegisterMouseClicked
// TODO add your handling code here:
    //Check the password and confirm password validity
    //check the username already exist in server
    //Send the username and password to the server
    //String Data = "Register:"+txt_Username.getText()+":"+txt_Password.getText();
    
    if(txt_Cfm_Password.getText().compareTo(txt_Password.getText()) == 0)
    {
        App.User_Login(1, txt_Username.getText(),txt_Password.getText());
    }
    else{
        this.Set_Warning("Password and Confirm password does not match");
    }
}//GEN-LAST:event_btn_RegisterMouseClicked

private void btn_CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelMouseClicked
// TODO add your handling code here:
    //Close the application
    try{
        this.setVisible(false);
        this.dispose();
    }
    catch(Exception e)
    {}
    System.exit(0);
}//GEN-LAST:event_btn_CancelMouseClicked

private void btn_RegCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RegCancelMouseClicked
// TODO add your handling code here:
    //Close the application
    try{
        this.setVisible(false);
        this.dispose();
    }
    catch(Exception e)
    {}
    System.exit(0);
    
}//GEN-LAST:event_btn_RegCancelMouseClicked

private void btn_NewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_NewUserMouseClicked
// TODO add your handling code here:
    
    //Hide and Enable the Buttons
    btn_Register.setVisible(true);
    lbl_Warning.setVisible(false);
    lbl_CfmPassword.setVisible(true);
    txt_Cfm_Password.setVisible(true);
    btn_RegCancel.setVisible(true);
    
    
    btn_Login.setVisible(false);
    btn_NewUser.setVisible(false);
    btn_Cancel.setVisible(false);
}//GEN-LAST:event_btn_NewUserMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_NewUser;
    private javax.swing.JButton btn_RegCancel;
    private javax.swing.JButton btn_Register;
    private javax.swing.JLabel lbl_CfmPassword;
    private javax.swing.JLabel lbl_Password;
    private javax.swing.JLabel lbl_Username;
    private javax.swing.JLabel lbl_Warning;
    private javax.swing.JTextField txt_Cfm_Password;
    private javax.swing.JTextField txt_Password;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
