/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MessengerApp_View.java
 *
 * Created on Apr 28, 2012, 8:17:30 PM
 */
package messengerproject;

/**
 *
 * @author alagaranandrajendran
 */
public class MessengerApp_View extends javax.swing.JFrame {

    String[] Names_List;
    
    MessengerProject Msg_App_Main;

    /** Creates new form MessengerApp_View */
    public MessengerApp_View(MessengerProject App) {
        this.Names_List = new String[0];
        initComponents();
        lbl_Warning.setVisible(false);
        Msg_App_Main = App;
        List_Clients.setListData(Names_List);
        setTitle(Msg_App_Main.Get_UserName());
    }
    
    
    
    public void Update_Clients(String[] Names_List)
    {
        this.Names_List = Names_List;
        List_Clients.setListData(Names_List);
    }
    
    public void Set_Warning(String Msg)
    {
        lbl_Warning.setText(Msg);
        lbl_Warning.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_StartSession = new javax.swing.JButton();
        btn_Logout = new javax.swing.JButton();
        lbl_Warning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_Clients = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_StartSession.setText("Start Session");
        btn_StartSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_StartSessionMouseClicked(evt);
            }
        });

        btn_Logout.setText("Logout");
        btn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseClicked(evt);
            }
        });

        lbl_Warning.setForeground(new java.awt.Color(255, 0, 0));
        lbl_Warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Warning.setText("Close all the sessions before logging out");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(62, 62, 62)
                .add(btn_StartSession)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 65, Short.MAX_VALUE)
                .add(btn_Logout)
                .add(118, 118, 118))
            .add(jPanel1Layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(lbl_Warning, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 390, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn_StartSession, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .add(btn_Logout, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(11, 11, 11)
                .add(lbl_Warning, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        List_Clients.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(List_Clients);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn_StartSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_StartSessionMouseClicked
// TODO add your handling code here:
    lbl_Warning.setVisible(false);
    
    if(List_Clients.getSelectedIndex() >=0)
    {
        String SelectedValue = (String)List_Clients.getSelectedValue();
        Msg_App_Main.Start_Session(SelectedValue);
    }
}//GEN-LAST:event_btn_StartSessionMouseClicked

private void btn_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseClicked
// TODO add your handling code here:
    lbl_Warning.setVisible(false);
    //Client Exit
    if(Msg_App_Main.Exit_Application())
    {
        try{
            this.setVisible(false);
            this.dispose();
        }
        catch(Exception e)
        {}
        
        System.exit(0);
    }
    else{
        lbl_Warning.setText("Close all the sessions before logging out");
        lbl_Warning.setVisible(true);
    }
}//GEN-LAST:event_btn_LogoutMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList List_Clients;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_StartSession;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Warning;
    // End of variables declaration//GEN-END:variables
}
